#!/usr/bin/env python3
"""Mock agent stub — a no-token stand-in for `opencode run --agent <name>`.

It reproduces exactly what the real agents do (writes its output files and its
control sidecar) so a flow can be demonstrated end to end without any model
calls. Selected via runtime="mock".

Control sidecar contract (what every agent writes to CONTROL_FILE):
  ENVELOPE (the engine reads): `status` (required), `agent`, `reason`,
    `rerun_required` (a flow-control signal a gate consumes).
  PAYLOAD (only gates/callers read): `result` — a free-form object holding
    agent-specific structured data (e.g. issues_found, key_points). The engine
    never looks inside `result`. There is deliberately NO `artifact` field: what
    an agent produces is its own business, expressed in files it was told to
    write — not reported back through the control file.

It also understands two fault-injection knobs, so you can watch the
orchestrator's timeout/retry/resume behaviour without real agents:

  MOCK_HANG=<agent>   -> that agent sleeps forever (tests the timeout/kill path)
  MOCK_FAIL=<agent>   -> that agent emits a failure control line (tests retry)

The prompt is passed as "KEY: value" lines (TOPIC / OUTPUT / REPORT), matching
what the flow sends to the real agents.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from pathlib import Path


def _kv(prompt: str, key: str) -> str | None:
    m = re.search(rf"^{key}:\s*(.+)$", prompt, re.MULTILINE)
    return m.group(1).strip() if m else None


def _report_path(prompt: str, default_name: str, *, key: str = "REPORT") -> Path:
    """Resolve where the mock writes its output file.

    An explicit path (from `key`, default REPORT) wins. Otherwise the fallback is
    anchored to the run_dir — the directory of the CONTROL_FILE (the sidecar
    always lives under run_dir) — NOT a bare relative name. A relative name would
    resolve against the subprocess cwd (= agent_dir), littering the
    agent-definitions tree; anchoring to the sidecar keeps artifacts with the run
    where they belong.
    """
    explicit = _kv(prompt, key)
    if explicit:
        return Path(explicit)
    control = _kv(prompt, "CONTROL_FILE")
    base = Path(control).parent if control else Path.cwd()
    return base / default_name


def _maybe_fault(agent: str, prompt: str) -> None:
    if os.environ.get("MOCK_HANG") == agent:
        time.sleep(100000)  # simulate a hang; the orchestrator must kill us
        # unreachable — but if somehow reached, return so MOCK_FAIL doesn't fire
        return
    if os.environ.get("MOCK_FAIL") == agent:  # elif would also be correct; explicit return above is clearer
        # Signal a CONTENT failure the way a real agent does: write an error
        # STATUS SIDECAR (not a stdout line), then exit non-zero.
        report = _report_path(prompt, f"{agent}.md")
        _write_sidecar(prompt, {"status": "error", "agent": agent, "reason": "injected failure"}, report)
        raise SystemExit(1)


def run_analyst(prompt: str) -> None:
    topic = _kv(prompt, "TOPIC") or "unknown topic"
    output = _report_path(prompt, "analysis.md", key="OUTPUT")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        f"# Analysis: {topic}\n\n"
        "## Summary\n"
        f"A concise mock analysis of {topic}. Generated by the mock agent for pipeline demonstration.\n\n"
        "## Key Points\n"
        "- The orchestration is deterministic Python, not an LLM.\n"
        "- Each agent runs as a supervised subprocess with liveness supervision.\n"
        "- Status is reported via a per-agent sidecar JSON file.\n\n"
        "## Risks / Open Questions\n"
        "- Mock output only; replace runtime=mock with runtime=opencode for real analysis.\n"
    )
    print(f"[mock analyst] wrote {output}")
    _write_sidecar(prompt, {"status": "ok", "agent": "analyst"}, output)


def run_verifier(prompt: str) -> None:
    report = _report_path(prompt, "analysis.md")
    text = report.read_text() if report.exists() else ""
    issues_found = 0
    if "## Verification" not in text:
        report.write_text(text + "\n## Verification\n- Status: verified\n- Issues found: 0\n- Notes: mock verification pass\n")
    print(f"[mock verifier] verified {report}")
    _write_sidecar(prompt, {"status": "verified", "agent": "verifier", "result": {"issues_found": issues_found}}, report)


def run_extractor(prompt: str) -> None:
    report = _report_path(prompt, "analysis.md")
    output = _report_path(prompt, "analysis.json", key="OUTPUT")
    text = report.read_text() if report.exists() else ""
    topic_m = re.search(r"^# Analysis:\s*(.+)$", text, re.MULTILINE)
    key_points_section = text.split("## Key Points")[-1].split("##")[0] if "## Key Points" in text else ""
    points = re.findall(r"^- (.+)$", key_points_section, re.MULTILINE)
    data = {
        "topic": topic_m.group(1).strip() if topic_m else "unknown",
        "summary": "Mock-extracted summary.",
        "key_points": points,
        "risks": ["Mock output only."],
        "verification": {"status": "verified", "issues_found": 0},
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(data, indent=2))
    print(f"[mock extractor] wrote {output}")
    _write_sidecar(prompt, {"status": "ok", "agent": "extractor", "result": {"key_points": len(points)}}, output)


DISPATCH = {"analyst": run_analyst, "verifier": run_verifier, "extractor": run_extractor}


# ---------------------------------------------------------------------------
# Tech-assessment mock agents (PRODUCT_KEY / REPORT prompt convention)
# ---------------------------------------------------------------------------
#
# These mimic tech-assessment agents: an analyst writes a report keyed by the
# PRODUCT_KEY; a verifier appends a `## Verification` block. To exercise the
# orchestrator's re-run loop, set MOCK_RERUN=<report-file> — the verifier for
# that report appends a `## Re-run Required` block ONCE (it clears a marker file
# so the second pass is clean, proving the bounded loop terminates).


def _is_tech_analyst(agent: str) -> bool:
    return agent.endswith("-analyst") or agent == "executive-summary"


def _is_tech_verifier(agent: str) -> bool:
    return agent.endswith("-verifier")


def _write_sidecar(prompt: str, payload: dict, fallback_report: Path) -> None:
    """Write the control sidecar to CONTROL_FILE (default: <report>.control.json).

    payload is the envelope (status/agent/reason/rerun_required) plus an optional
    free-form `result` object. No `artifact` field — see the module docstring.
    """
    control = _kv(prompt, "CONTROL_FILE")
    path = Path(control) if control else fallback_report.with_suffix(".control.json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload))


def run_tech_analyst(agent: str, prompt: str) -> None:
    product = _kv(prompt, "PRODUCT_KEY") or "unknown-product"
    report = _report_path(prompt, f"{agent}.md")
    # A one-time instruction (from a gate's Restart/GoTo `instruction`) is injected
    # VERBATIM into the prompt by the engine — there is no fixed key/heading (the
    # caller owns the framing). For test/demo visibility, echo it into the report
    # when the caller marked it with the "ONE_TIME:" convention. Absent it, the
    # mechanism still works; the mock simply has nothing distinctive to echo.
    one_time = _kv(prompt, "ONE_TIME")
    report.parent.mkdir(parents=True, exist_ok=True)
    note = f"\n> One-time instruction addressed: {one_time}\n" if one_time else ""
    report.write_text(
        f"# {report.stem} — {product}\n{note}\n"
        "## Summary\n"
        f"Mock {agent} analysis for product '{product}'.\n\n"
        "## Findings\n"
        f"- Produced by {agent} in the deterministic Prefect DAG.\n"
        f"- Product key '{product}' was threaded through the prompt.\n"
    )
    # A small structured result. It happens to satisfy the tech-stack demo
    # schema (summary + languages); other stages carry no schema, so the extra
    # fields are simply ignored.
    result = {"summary": f"Mock {agent} analysis for '{product}'.", "languages": ["Python", "TypeScript"]}
    _write_sidecar(prompt, {"status": "ok", "agent": agent, "result": result}, report)
    print(f"[mock {agent}] wrote {report} + sidecar for product={product}")


def run_tech_verifier(agent: str, prompt: str) -> None:
    report = _report_path(prompt, "report.md")
    text = report.read_text() if report.exists() else ""
    if "## Verification" not in text:
        report.write_text(text + "\n## Verification\n- Status: verified\n- Issues found: 0\n")

    # Optional re-run injection to exercise the bounded loop, ONCE (via sidecar).
    marker = report.with_suffix(".rerun_pending")
    inject_for = os.environ.get("MOCK_RERUN", "")
    if inject_for and report.name == inject_for and not marker.exists():
        marker.write_text("1")
        analyst = f"{report.stem}-analyst" if agent != "summary-verifier" else "executive-summary"
        _write_sidecar(prompt, {"status": "verified", "agent": agent, "rerun_required": [analyst]}, report)
        print(f"[mock {agent}] verified {report} + sidecar rerun_required")
        return

    marker.unlink(missing_ok=True)
    _write_sidecar(prompt, {"status": "verified", "agent": agent}, report)
    print(f"[mock {agent}] verified {report} (clean) + sidecar")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--agent", required=True)
    ap.add_argument("--prompt", required=True)
    ap.add_argument("--model", required=False, default="")
    args = ap.parse_args()

    _maybe_fault(args.agent, args.prompt)

    # Tech-assessment agents (name-suffix routing) take priority.
    if _is_tech_verifier(args.agent):
        run_tech_verifier(args.agent, args.prompt)
        return
    if _is_tech_analyst(args.agent):
        run_tech_analyst(args.agent, args.prompt)
        return

    handler = DISPATCH.get(args.agent)
    if handler is None:
        # No sidecar written -> the supervisor treats it as an error. Print a
        # human hint to stderr (stdout is the event stream) and exit non-zero.
        print(f"[mock] unknown agent {args.agent!r}", file=sys.stderr)
        raise SystemExit(2)
    handler(args.prompt)


if __name__ == "__main__":
    main()
